//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mop.Configurator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mop.Configurator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Program ProgramName=&quot;mop.Configurator&quot; Description=&quot;Конфигурация приложений&quot; DefaultConfigurationName=&quot;DefaultConfiguration&quot; ProgramTypeName=&quot;Модуль&quot;&gt;
        ///  &lt;HostTypes&gt;
        ///    &lt;HostType Name=&quot;Сервер&quot;&gt;&lt;/HostType&gt;
        ///    &lt;HostType Name=&quot;АРМ&quot;&gt;&lt;/HostType&gt;
        ///  &lt;/HostTypes&gt;
        ///  &lt;Types&gt;  
        ///  &lt;/Types&gt;
        ///  &lt;Parameters&gt;
        ///    &lt;Parameter Name=&quot;FileImportManager&quot; ValueTypeName=&quot;ParameterSet&quot; IsRequired=&quot;True&quot; IsVisible=&quot;True&quot; IsReadOnly=&quot;True&quot; Description=&quot;Параметры технического журналиров [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mop_Configurator {
            get {
                return ResourceManager.GetString("mop_Configurator", resourceCulture);
            }
        }
    }
}
